#include "plugin.hpp"

struct LFO_1 : Module {
	enum ParamIds {
		FREQKNOB_PARAM,
		PULSEWIDTHKNOB_PARAM,
		FM1KNOB_PARAM,
		FM2KNOB_PARAM,
		PWMKNOB_PARAM,
		WAVETYPE1_PARAM,
		WAVETYPE2_PARAM,
		WAVETYPE3_PARAM,
		WAVETYPE4_PARAM,
		WAVECV1_PARAM,
		WAVECV2_PARAM,
		WAVECV3_PARAM,
		WAVECV4_PARAM,
		VOLTAGEMODE_PARAM,
		PHASE_PARAM,
		NUM_PARAMS
	};

	enum InputIds {
		FM1JACK_INPUT,
		FM2JACK_INPUT,
		PWMJACK_INPUT,
		RESETJACK_INPUT,
		NUM_INPUTS
	};

	enum OutputIds {
		SINEWAVEJACK_OUTPUT,
		TRIANGLEWAVEJACK_OUTPUT,
		SAWWAVEJACK_OUTPUT,
		SQUAREWAVEJACK_OUTPUT,
		NUM_OUTPUTS
	};

	enum LightIds {
		BLINK_LIGHT,
		NUM_LIGHTS
	};
    
};
